# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(020000)
$foreground = rgb(E9DACE)
$color0 = rgb(020000)
$color1 = rgb(2A2526)
$color2 = rgb(4C3B2F)
$color3 = rgb(503F31)
$color4 = rgb(654932)
$color5 = rgb(7A604A)
$color6 = rgb(8F7157)
$color7 = rgb(D6C2B1)
$color8 = rgb(96887C)
$color9 = rgb(383133)
$color10 = rgb(654F3E)
$color11 = rgb(6B5341)
$color12 = rgb(876143)
$color13 = rgb(A38063)
$color14 = rgb(BF9674)
$color15 = rgb(D6C2B1)
