# preload = /usr/share/backgrounds/ubuntu-wallpaper-d.png
# wallpaper = /usr/share/backgrounds/ubuntu-wallpaper-d.png

source = $HOME/.config/hypr/configs/vars.conf

$wp = /usr/share/backgrounds/ubuntu-wallpaper-d.png
preload = $wp

splash = false

wallpaper {
    monitor = eDP-1
    path = $wp
}

wallpaper {
    monitor = $monitor
    path = $wp
}

# wallpaper {
#     monitor = DP-6
#     path = /usr/share/backgrounds/ubuntu-wallpaper-d.png
# }
